### ISSUE TITLE
Some of these PDF's are very confusing 🤔

### ISSUE THREAD

**Issue by Sopor** [ACE-AU/OGX-PIII-CPU-VCORE-SETTINGS#1]
Some of these PDF's are very confusing.

In the `Xbox V1.2-1.4 VCORE Mod.pdf` it sometimes says V1.4 and sometimes V1.40, sometimes V1.5 and sometimes V1.50.

You never know if is it version or voltage 😢

Shouldn't version be in front of the value and voltage be after, v1.4 and 1.4v?

Some kind of consistency would have been great 😊

`OPTION 2 For V1.8 Focus Encoder VCC` is this voltage or version? I assume it is voltage, but doesn't the Focus chip runs on 1.5 volt?

**Comment by ACE-AU** [comment]
I have updated the file

**Comment by Sopor** [comment]
Thank you! 😘
